<a href="https://colab.research.google.com/github/Stamatics-NumberstoNeurons/assignment1-basicpythonandnumpy-sanjay-ml/blob/main/numpy_worksheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Exercises — 50 Problems

**Instructions:**
- Run the first cell to import NumPy before starting.
- Each exercise has a **Question** and an **Input** (where given).
- Write your solution in the `# Write your code here:` cell below each question.
- Run your cell to check your output.
- Do **not** modify the Input cells or the import cell.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [4]:
# Run this cell before starting — do not modify
import numpy as np

## Section 1 — Array Basics (Exercises 1–10)

### Exercise 1 — NumPy Version

**Question:** Print the version of NumPy.


In [ ]:
# Write your code here:
print(np.__version__)

2.0.2


### Exercise 2 — 1D Array

**Question:** Create a 1D array of numbers from 0 to 9.


In [ ]:
# Write your code here:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


### Exercise 3 — Boolean Array

**Question:** Create a 3×3 NumPy array of all `True`s.


In [ ]:
# Write your code here:
arr = np.ones((3,3), dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Exercise 4 — Filter Odd Numbers

**Question:** Extract all odd numbers from `arr`.


In [ ]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Write your code here:
arr=arr[arr%2==1]
print(arr)

[1 3 5 7 9]


### Exercise 5 — Replace In-Place

**Question:** Replace all odd numbers in `arr` with `-1`.


In [ ]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Write your code here:
for i in range(len(arr)):
  if arr[i]%2!=0:
    arr[i]=-1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 6 — Replace Without Modifying Original

**Question:** Replace all odd numbers in `arr` with `-1` **without** changing the original array.


In [ ]:
# Input — do not modify
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Write your code here:
arr1=arr.copy()
for i in range(len(arr1)):
  if arr1[i]%2!=0:
    arr1[i]=-1
print(arr1)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


### Exercise 7 — Reshape Array

**Question:** Convert a 1D array to a 2D array with 2 rows.


In [ ]:
# Input — do not modify
arr = np.arange(10)

In [ ]:
# Write your code here:
arr_2d=arr.reshape(2,5)
print(arr_2d)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Exercise 8 — Vertical Stack

**Question:** Stack arrays `a` and `b` vertically.


In [ ]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)


In [ ]:
# Write your code here:
result=np.vstack((a,b))
print(result)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Exercise 9 — Horizontal Stack

**Question:** Stack arrays `a` and `b` horizontally.


In [ ]:
# Input — do not modify
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [ ]:
# Write your code here:
result=np.hstack((a,b))
print(result)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Exercise 10 — Custom Sequence

**Question:** Create the following pattern **without hardcoding**. Use only NumPy functions and the input array `a`.

Expected output: `array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`


In [ ]:
# Input — do not modify
a = np.array([1, 2, 3])

In [ ]:
# Write your code here:
result=np.concatenate((np.repeat(a,3),np.tile(a,3)))
print(result)

[1 1 1 2 2 2 3 3 3 1 2 3 1 2 3 1 2 3]


## Section 2 — Set Operations & Filtering (Exercises 11–19)

### Exercise 11 — Common Items

**Question:** Get the common items between arrays `a` and `b`.


In [ ]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [ ]:
# Write your code here:
result=np.intersect1d(a,b)
print(result)

[2 4]


### Exercise 12 — Remove Items

**Question:** From array `a`, remove all items present in array `b`.


In [5]:
# Input — do not modify
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [6]:
# Write your code here:
a=a[~np.isin(a,b)]
print(a)

[1 2 3 4]


### Exercise 13 — Matching Positions

**Question:** Get the positions where elements of `a` and `b` match.


In [7]:
# Input — do not modify
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [13]:
# Write your code here:
np.where(a==b)

(array([1, 3, 5, 7]),)

### Exercise 14 — Extract Range

**Question:** Get all items between 5 and 10 from array `a`.


In [20]:
# Input — do not modify
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [30]:
# Write your code here:
a[(a>5)&(a<10)].tolist()

[6, 9]

### Exercise 15 — Vectorize a Function

**Question:** Convert the scalar function `maxx` below to work on two arrays.


In [31]:
# Input — do not modify
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [33]:
# Write your code here:
vmax=np.vectorize(maxx)
vmax(a,b).tolist()

[6, 7, 9, 8, 9, 7, 5]

### Exercise 16 — Swap Columns

**Question:** Swap columns 1 and 2 in array `arr`.


In [51]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)


In [45]:
# Write your code here:
arr[:,[0,1]]=arr[:,[1,0]]
print(arr)

[[1 0 2]
 [4 3 5]
 [7 6 8]]


### Exercise 17 — Swap Rows

**Question:** Swap rows 1 and 2 in array `arr`.


In [46]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [50]:
# Write your code here:
arr[[0,1],:]=arr[[1,0],:]
print(arr)

[[3 4 5]
 [0 1 2]
 [6 7 8]]


### Exercise 18 — Reverse Rows

**Question:** Reverse the rows of the 2D array `arr`.


In [60]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)


In [57]:
# Write your code here:
arr=arr[::-1]
print(arr)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


### Exercise 19 — Reverse Columns

**Question:** Reverse the columns of the 2D array `arr`.


In [67]:
# Input — do not modify
arr = np.arange(9).reshape(3,3)

In [66]:
arr = np.arange(9).reshape(3,3)
arr=arr[:, ::-1]
print(arr)

[[2 1 0]
 [5 4 3]
 [8 7 6]]


## Section 3 — Printing & Formatting (Exercises 20–24)

### Exercise 20 — Random Float Array

**Question:** Create a 2D array of shape 5×3 containing random decimal numbers between 5 and 10.


In [73]:
# Write your code here:
a=np.random.uniform(5,10, (5,3))
print(a)

[[5.40758586 9.28400706 5.58473903]
 [7.01597593 7.46565316 6.2624166 ]
 [5.77368036 5.50206249 8.28798567]
 [9.90754115 7.90395702 6.78931543]
 [7.58932805 5.00398128 5.52869051]]


### Exercise 21 — Decimal Places

**Question:** Print only 3 decimal places of the array `rand_arr`.


In [77]:
# Input — do not modify
rand_arr = np.random.random((5,3))

In [78]:
# Write your code here:
rand_arr=rand_arr.round(3)
print(rand_arr)

[[0.501 0.166 0.862]
 [0.143 0.1   0.467]
 [0.575 0.086 0.511]
 [0.438 0.648 0.167]
 [0.112 0.034 0.07 ]]


### Exercise 22 — Suppress Scientific Notation

**Question:** Pretty print `rand_arr` by suppressing scientific notation (like `1e10`).


In [86]:
# Input — do not modify
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3

In [88]:
# Write your code here:
np.set_printoptions(suppress=True)
print(rand_arr)

[[0.0005434  0.00027837 0.00042452]
 [0.00084478 0.00000472 0.00012157]
 [0.00067075 0.00082585 0.00013671]]


### Exercise 23 — Limit Print Output

**Question:** Limit the number of items printed in array `a` to a maximum of 6 elements.


In [91]:
# Input — do not modify
a = np.arange(15)

In [92]:
# Write your code here:
np.set_printoptions(threshold=6)
print(a)

[ 0  1  2 ... 12 13 14]


### Exercise 24 — Print Full Array

**Question:** Print the full NumPy array `a` without truncating.


In [93]:
# Input — do not modify
np.set_printoptions(threshold=6)
a = np.arange(15)

In [94]:
# Write your code here:
np.set_printoptions(threshold=np.inf)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


## Section 4 — Iris Dataset (Exercises 25–46)

### Exercise 25 — Import Dataset

**Question:** Import the Iris dataset keeping the text intact.

> URL: `https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv`


In [95]:
# Write your code here:
url="https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv"
iris=np.genfromtxt(url, delimiter=',', dtype='object')
print(iris)

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']
 [b'5.4' b'3.7' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'Iris-setosa']
 [b'4.8' b'3.0' b'1.4' b'0.1' b'Iris-setosa']
 [b'4.3' b'3.0' b'1.1' b'0.1' b'Iris-setosa']
 [b'5.8' b'4.0' b'1.2' b'0.2' b'Iris-setosa']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.3' b'0.4' b'Iris-setosa']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.7' b'3.8' b'1.7' b'0.3' b'Iris-setosa']
 [b'5.1' b'3.8' b'1.5' b'0.3' b'Iris-setosa']
 [b'5.4' b'3.4' b'1.7' b'0.2' b'Iris-setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b'Ir

### Exercise 26 — Extract Text Column

**Question:** Extract the text column `species` from the 1D iris dataset imported in Exercise 25.

*# Make sure you have run Exercise 25 first so that iris_data is defined.*


In [96]:
# Write your code here:
species=iris[:,4]
print(species)

[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-versicolor' b'Iris-versicolor'
 b'Iris-versicolor' b'Iris-versicolor' b'Iris-versicolor'
 b'Iris-versicolor' b'Iris-versicolor' b'Iris-versicolor'
 b'Iris-versicolor' b'Iris-versicolor' b'Iris-versicolor'
 b'Iris-versicolor' b'Iri

### Exercise 27 — 1D to 2D Array

**Question:** Convert the 1D iris dataset to a 2D array `iris_2d` by omitting the species text field.

*# Make sure you have run Exercise 25 first.*


In [97]:
# Write your code here:
iris_2d=iris[:,:4].astype('float')
print(iris_2d)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

### Exercise 28 — Mean, Median, Std

**Question:** Find the mean, median, and standard deviation of the sepal length (1st column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [99]:
# Write your code here:
col=iris_2d[:,0]
print("Mean  :",np.mean(col))
print("Median:",np.median(col))
print("Std   :",np.std(col))

Mean  : 5.843333333333334
Median: 5.8
Std   : 0.8253012917851409


### Exercise 29 — Normalize Array

**Question:** Create a normalized form of iris's sepal length whose values range exactly between 0 and 1 (minimum → 0, maximum → 1).

*# Make sure you have run Exercise 27 first.*


In [100]:
# Write your code here:
col=iris_2d[:,0]
normalized=(col-col.min())/(col.max()-col.min())
print(normalized)

[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 0.55555556 0.36111111 0.33333333
 0.33333

### Exercise 30 — Softmax Score

**Question:** Compute the softmax score of the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [102]:
# Write your code here:
softmax= np.exp(col)/np.sum(np.exp(col))
print(softmax)

[0.00221959 0.00181724 0.00148783 0.00134625 0.00200836 0.00299613
 0.00134625 0.00200836 0.00110221 0.00181724 0.00299613 0.00164431
 0.00164431 0.00099732 0.0044697  0.00404435 0.00299613 0.00221959
 0.00404435 0.00221959 0.00299613 0.00221959 0.00134625 0.00221959
 0.00164431 0.00200836 0.00200836 0.00245302 0.00245302 0.00148783
 0.00164431 0.00299613 0.00245302 0.00331123 0.00181724 0.00200836
 0.00331123 0.00181724 0.00110221 0.00221959 0.00200836 0.00121813
 0.00110221 0.00200836 0.00221959 0.00164431 0.00221959 0.00134625
 0.00271101 0.00200836 0.01483991 0.00814432 0.01342771 0.00331123
 0.00900086 0.00404435 0.00736928 0.00181724 0.00994749 0.00245302
 0.00200836 0.00493978 0.0054593  0.00603346 0.00365948 0.01099368
 0.00365948 0.0044697  0.006668   0.00365948 0.00493978 0.00603346
 0.00736928 0.00603346 0.00814432 0.00994749 0.01214989 0.01099368
 0.0054593  0.00404435 0.00331123 0.00331123 0.0044697  0.0054593
 0.00299613 0.0054593  0.01099368 0.00736928 0.00365948 0.00331

### Exercise 31 — Percentile Scores

**Question:** Find the 5th and 95th percentile of iris's sepal length.

*# Make sure you have run Exercise 27 first.*


In [103]:
# Write your code here:
p5=np.percentile(col, 5)
p95=np.percentile(col, 95)
print("5th percentile:",p5)
print("95th percentile:",p95)

5th percentile: 4.6
95th percentile: 7.254999999999998


### Exercise 32 — Insert Missing Values

**Question:** Insert `np.nan` values at 20 random positions in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


### Exercise 33 — Find Missing Values

**Question:** Find the **number** and **position** of missing values in `iris_2d`'s sepal length (1st column).

*# Make sure you have run Exercise 32 first.*


In [ ]:
# Write your code here:


### Exercise 34 — Multi-Condition Filter

**Question:** Filter the rows of `iris_2d` that have:
- petal length (3rd column) > 1.5, **and**
- sepal length (1st column) < 5.0

*# Make sure you have run Exercise 32 first.*


In [ ]:
# Write your code here:


### Exercise 35 — Drop Rows with NaN

**Question:** Select rows of `iris_2d` that do **not** have any `nan` value.

*# Make sure you have run Exercise 32 first.*


In [ ]:
# Write your code here:


### Exercise 36 — Correlation

**Question:** Find the correlation between sepal length (1st column) and petal length (3rd column) in `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


### Exercise 37 — Check for NaN

**Question:** Find out if `iris_2d` has any missing values.

*# Make sure you have run Exercise 32 first.*


In [ ]:
# Write your code here:


### Exercise 38 — Replace NaN with 0

**Question:** Replace all occurrences of `nan` with `0` in `iris_2d`.

*# Make sure you have run Exercise 32 first.*


In [ ]:
# Write your code here:


### Exercise 39 — Unique Value Counts

**Question:** Find the unique values and their counts in iris's species column.

*# Make sure you have run Exercise 25 first.*


In [ ]:
# Write your code here:


### Exercise 40 — Numeric to Categorical

**Question:** Bin the petal length (3rd column) of `iris_2d` to form a text array using these rules:
- `< 3` → `'small'`
- `3–5` → `'medium'`
- `>= 5` → `'large'`

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


### Exercise 41 — Create New Column

**Question:** Create a new column for **volume** in `iris_2d`, where:

> volume = (π × petal_length × sepal_length²) / 3

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


### Exercise 42 — Probabilistic Sampling

**Question:** Randomly sample iris's species such that **setosa** appears **twice** as often as versicolor and virginica.

*# Make sure you have run Exercise 25 first.*


In [ ]:
# Write your code here:


### Exercise 43 — Second Largest Value

**Question:** Find the **second longest** petal length among iris samples of species **setosa**.

*# Make sure you have run Exercise 25 first.*


In [ ]:
# Write your code here:


### Exercise 44 — Sort 2D Array by Column

**Question:** Sort the iris dataset based on the sepal length column.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


### Exercise 45 — Most Frequent Value

**Question:** Find the most frequent value of petal length (3rd column) in the iris dataset.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


### Exercise 46 — First Value Greater Than

**Question:** Find the position of the **first occurrence** of a value greater than 1.0 in the petal width (4th column) of `iris_2d`.

*# Make sure you have run Exercise 27 first.*


In [ ]:
# Write your code here:


## Section 5 — Miscellaneous (Exercises 47–50)

### Exercise 47 — Clip Values

**Question:** From array `a`, replace all values **greater than 30** with `30`, and all values **less than 10** with `10`.


In [ ]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [ ]:
# Write your code here:


### Exercise 48 — Top N Positions

**Question:** Get the positions of the **top 5 maximum values** in array `a`.


In [ ]:
# Input — do not modify
np.random.seed(100)
a = np.random.uniform(1, 50, 20)

In [ ]:
# Write your code here:


### Exercise 49 — Row-wise Unique Counts

**Question:** Compute the counts of unique values **row-wise** in the input array.


In [ ]:
# Input — do not modify
np.random.seed(100)
arr = np.random.randint(1, 11, size=(6, 10))

In [ ]:
# Write your code here:


### Exercise 50 — Flatten Array of Arrays

**Question:** Convert `arr_2d` (an array of arrays) into a flat 1D array.


In [ ]:
# Input — do not modify
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)
arr_2d = np.array([arr1, arr2, arr3], dtype=object)

In [ ]:
# Write your code here:


---

## 🎉 Well done!

You've completed all 50 exercises. Review any exercises you found tricky and revisit the NumPy documentation for deeper understanding.